// Generated by https://quicktype.io

export interface RecipeData {
  recipe: Recipe[];
}

export interface Recipe {
  name: string;
  id: string;
  description: string;
  tag: string[];
  image: string;
  ingredient: Ingredient[];
  ingredientGroup?: IngredientGroup[];
  step: Step[];
  notes?: string;
  forked?: string;
}

export interface Ingredient {
  amount?: string;
  unit?: string;
  name?: string;
  preparation?: string;
}

export interface IngredientGroup {
  ingredient: Ingredient[];
  name?: string;
}

export interface Step {
  description: string;
}
