// Generated by https://quicktype.io

export interface Order {
  tableName: string;
  persons: number | null;
  choices: string[];
}

export interface OrdersMap {
  [tableName: string]: Order | null;
}
